obstacle_range: 2.5
raytrace_range: 3.0
#robot_radius: ir_of_robot
inflation_radius: 0.55

observation_sources: point_cloud_sensor

#laser_scan_sensor: {sensor_frame: frame_name, data_type: LaserScan, topic: topic_name, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: lidar3d_link , data_type: PointCloud2 , topic: /velodyne_points, marking: true, clearing: true}