local_costmap:
  plugins: 
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
  global_frame: camera_init
  robot_base_frame: camera
  update_frequency: 5.0
  publish_frequency: 2.0
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05